version: '3'
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    command: flask run --host=0.0.0.0 --port=8080 --reload 